import math


def main():
    enc_string = """eaweeeyteroosifdytulaoowyauonagdoewpaayauuvtiebbafdytoyolirghnoretdeoeieoiaogonvenalahuahudhrtusoveecowalmkvhoaottaynttiaeaechidaosaunmyyuyroowifdyyundneaatunhnvopthyisiulyeaiooliylmeeswgaeongaebmipoetlsmaiutioullolayyfeeeodmrpbwnaormaeetomaemistlmuco*nuifeetcrntcodiiloyunrcfupelinernhhcouiaehnctuusriiounasetudieepiostseagathsnoetyoigeoyhoatbksoasmwotvydnmmstsbaehbnteiiayeoh*irrylbeifosiflytuyloopiiounasevencaigjnbmtihtbogfyycpoeennrghgiatyirehhnsewuitnstofngcatctiacerlteessuaiaiodsnewvwookreosaryt*asaermohgeuntwowiflyyunaoyruelaiulainnaugpeowyueiosyauonanwoegohmhoyoioegorktunernninesyesaeealfmomoapnwaoieiutnionotshtysyro*gncraraaolaortcfduillaooliylmojeaaayusgbtigaotkoacfupelighiomtnrkuchtetanmaoirgdounytuayuyhyowwttaeuoeaonnooheeyroetoetilsnur*heekpmvrdfdyyuliorfcfdytcpoeenifannnaaletnhgnuynalauuzryoicncohduthuhttieltofstungaiailiiswbaogrnwdrtowywenigavaaetdlhemtdade*titseeueoillaonacodiilliuuzryotfwuncnnlsoituaotidntoyruelgeipttabatotsnliniyorojeanvnntwntyystdoeraunyaayrddnciehbtuatrsiesem*rershrlheecfduilliontcfdytoyoletyviawwlcodosevuprillsyslltantimelwnsmutflteonyoifawhwwjdwjluuooemawditoypoaityhgamwdeisejhdbngbsenmelgshiiloyunawosiillsysllnstadeuiftyeltsooefdundneaatcinosvboouslomophtohstfwisupdludloopcyrseasslatnteettnhoinvetmstymau
"""

    enc_string = enc_string.replace(" ", "").replace("\n", "").strip().upper()
    key_len = 10
    num_rows = math.ceil(len(enc_string) / key_len)
    string = ""
    for row in range(num_rows):
        string += enc_string[row::num_rows]
    print(string)


if __name__ == "__main__":
    main()
